# Generated by Django 2.2.9 on 2022-11-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221031_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'название группы', 'verbose_name_plural': 'Группы'},
        ),
    ]
